version: '3.8'

networks:
  arcmedia:

services:
  nginx:
    container_name: arcmedia_nginx
    image: nginx:stable-alpine
    ports:
      - '8081:80'
    volumes:
      - .:/var/www/html/public:delegated
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
    networks:
      - arcmedia

  database:
    container_name: arcmedia_database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: arcmedia
      MYSQL_USER: cristian
      MYSQL_PASSWORD: secret
    ports:
      - '4306:3306'
    volumes:
      - arcmedia_db:/var/lib/mysql
    networks:
      - arcmedia

  php:
    container_name: arcmedia_php
    build:
      context: docker/php
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www/html:delegated
    depends_on:
      - database
    networks:
      - arcmedia

  composer:
    container_name: arcmedia_composer
    image: composer:2
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - php
    entrypoint: [ 'composer' ]
    networks:
      - arcmedia

volumes:
  arcmedia_db: